#!/usr/bin/zsh
GRAL=$(pwd)

ln -sf $GRAL/zshrc $HOME/.zshrc
ln -sf $GRAL/tmux.conf $HOME/.tmux.conf

mkdir -p $HOME/.config/nvim
ln -sf $GRAL/vimrc $HOME/.config/nvim/init.vim
ln -sf $GRAL/coc.json $HOME/.config/nvim/coc-settings.json

mkdir -p $HOME/.config/lf
ln -sf $GRAL/lfrc $HOME/.config/lf/lfrc
ln -sf $GRAL/pv.sh $HOME/.config/lf/pv.sh

mkdir -p $HOME/.oh-my-zsh/custom/themes
ln -sf $GRAL/custom.zsh-theme $HOME/.oh-my-zsh/custom/themes/custom.zsh-theme
