#!/usr/bin/zsh
GRAL=$(pwd)

mkdir -p $HOME/.config/nvim
ln -sf $GRAL/nvim/vimrc $HOME/.vimrc

mkdir -p $HOME/.config/lf
ln -sf $GRAL/lf/lfrc $HOME/.config/lf/lfrc
ln -sf $GRAL/lf/pv.sh $HOME/.config/lf/pv.sh

mkdir -p $HOME/.oh-my-zsh/custom/themes
ln -sf $GRAL/custom.zsh-theme $HOME/.oh-my-zsh/custom/themes/custom.zsh-theme
