#!/usr/bin/zsh
GRAL=$(pwd)
ln -sf $GRAL/vim.conf $HOME/.vimrc
ln -sf $GRAL/coc.conf $HOME/.vim/coc-settings.json
ln -sf $GRAL/zsh.conf $HOME/.zshrc
ln -sf $GRAL/xinit.conf $HOME/.xinitrc
ln -sf $GRAL/lf.conf $HOME/.config/lf/lfrc
ln -sf $GRAL/tmux.conf $HOME/.tmux.conf
ln -sf $GRAL/xmodmap.sh $HOME/.xmodmap.sh
ln -sf $GRAL/xmodmap.conf $HOME/.xmodmap.conf
ln -sf $GRAL/i3.conf $HOME/.config/i3/config
ln -sf $GRAL/i3status.conf $HOME/.config/i3status/config
ln -sf $GRAL/polybar.conf $HOME/.config/polybar/config.ini
ln -sf $GRAL/neofetch.conf $HOME/.config/neofetch/config.conf
ln -sf $GRAL/alacritty.conf $HOME/.config/alacritty/alacritty.yml
ln -sf $GRAL/custom.zsh-theme $HOME/.oh-my-zsh/custom/themes/custom.zsh-theme
