#!/usr/bin/zsh
GRAL=$(pwd)

ln -sf $GRAL/zshrc $HOME/.zshrc
ln -sf $GRAL/xinitrc $HOME/.xinitrc
ln -sf $GRAL/tmux.conf $HOME/.tmux.conf
ln -sf $GRAL/xmodmap.sh $HOME/.xmodmap.sh
ln -sf $GRAL/xmodmap.conf $HOME/.xmodmap.conf

mkdir -p $HOME/.config/nvim
ln -sf $GRAL/vimrc $HOME/.config/nvim/init.vim
ln -sf $GRAL/coc.json $HOME/.config/nvim/coc-settings.json

mkdir -p $HOME/.config/lf
ln -sf $GRAL/lf.conf $HOME/.config/lf/lfrc

mkdir -p $HOME/.config/i3
ln -sf $GRAL/i3.conf $HOME/.config/i3/config

mkdir -p $HOME/.config/polybar
ln -sf $GRAL/polybar.conf $HOME/.config/polybar/config.ini

mkdir -p $HOME/.config/neofetch
ln -sf $GRAL/neofetch.conf $HOME/.config/neofetch/config.conf

mkdir -p $HOME/.config/alacritty
ln -sf $GRAL/alacritty.yml $HOME/.config/alacritty/alacritty.yml

mkdir -p $HOME/.oh-my-zsh/custom/themes
ln -sf $GRAL/custom.zsh-theme $HOME/.oh-my-zsh/custom/themes/custom.zsh-theme
