font=JetBrainsMono Nerd Font 10
background-color=#282828dd
text-color=#ebdbb2ff
border-color=#458588ff
border-size=2
border-radius=12
padding=10
margin=12
width=360
height=110
default-timeout=3500
anchor=top-right
layer=overlay
icons=1
max-icon-size=32
max-visible=5
