#!/bin/bash

# basic tools
sudo add-apt-repository ppa:jonathonf/vim
sudo apt update
sudo apt install net-tools network-manager # nmcli device wifi
sudo apt install build-essential cmake python3-dev # pre for ycmd
sudo apt install xbindkeys x11-utils xdotool # keyboard utils
sudo apt install ranger zsh curl git vim vim-gtk3 exuberant-ctags fzf highlight tmux nodejs yarn fwupd xcape htop 
sudo apt install i3 xbacklight alsa-utils pulseaudio playerctl blueman feh lxappearance arc-theme arandr rofi compton
sudo apt install caca-utils highlight atool w3m poppler-utils mediainfo gnome-tweak-tool fprintd neofetch scrot
sudo apt install code google-chrome-stable xfce4-terminal python3-setuptools
sudo apt install texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-fonts-extra

curl -fsSL https://code-server.dev/install.sh | sh # code-server
PATH="$HOME/.local/bin:$PATH" # password set in dotfiles
# input setup manually added in chrome

# zsh and oh-my-zsh and set as default
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
chsh -s $(which zsh) # change default shell as zsh

# oh my zsh plugins, will be called in .zshrc in dotfiles
git clone https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions
git clone git://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
# apply rock setup immediately after this and reboot

# typora
wget -qO - https://typora.io/linux/public-key.asc | sudo apt-key add -
sudo add-apt-repository 'deb https://typora.io/linux ./'
sudo apt install typora

# nodejs
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
sudo apt-get install -y nodejs

# copy xmodmap.desktop
mkdir -p ~/.config/autostart
cp ./remap/xmodmap/xmodmap.desktop ~/.config/autostart

# fusuma
sudo gpasswd -a $USER input
sudo apt install libinput-tools ruby xdotool
sudo gem install fusuma

# show sys info
neofetch # showit!
